#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'postgresql'
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
